version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: toolpassword
      MYSQL_DATABASE: toolv2
      MYSQL_USER: tooluser
      MYSQL_PASSWORD: toolpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
