INSERT INTO toolv2.words (name,bonus,words,`rows`,`characters`,description,created_at,updated_at) VALUES

('Level 87','','BRICK,BRIDE,BRIDGE,BRIGHT,BRISK','{"characters":["B","R","I","C","K"],"rows":[[{"key":"B","words":["BRICK"],"isShow":false},{"key":"R","words":["BRICK"],"isShow":false},{"key":"I","words":["BRICK"],"isShow":false},{"key":"C","words":["BRICK"],"isShow":false},{"key":"K","words":["BRICK"],"isShow":false}],[{"key":"B","words":["BRIDE"],"isShow":false},{"key":"R","words":["BRIDE"],"isShow":false},{"key":"I","words":["BRIDE"],"isShow":false},{"key":"D","words":["BRIDE"],"isShow":false},{"key":"E","words":["BRIDE"],"isShow":false}],[{"key":"B","words":["BRIDGE"],"isShow":false},{"key":"R","words":["BRIDGE"],"isShow":false},{"key":"I","words":["BRIDGE"],"isShow":false},{"key":"D","words":["BRIDGE"],"isShow":false},{"key":"G","words":["BRIDGE"],"isShow":false},{"key":"E","words":["BRIDGE"],"isShow":false}],[{"key":"B","words":["BRIGHT"],"isShow":false},{"key":"R","words":["BRIGHT"],"isShow":false},{"key":"I","words":["BRIGHT"],"isShow":false},{"key":"G","words":["BRIGHT"],"isShow":false},{"key":"H","words":["BRIGHT"],"isShow":false},{"key":"T","words":["BRIGHT"],"isShow":false}],[{"key":"B","words":["BRISK"],"isShow":false},{"key":"R","words":["BRISK"],"isShow":false},{"key":"I","words":["BRISK"],"isShow":false},{"key":"S","words":["BRISK"],"isShow":false},{"key":"K","words":["BRISK"],"isShow":false}]]}','B,R,I,C,K','BRICK: A small rectangular block used in building.
BRIDE: A woman on her wedding day.
BRIDGE: A structure built to span a physical obstacle.
BRIGHT: Giving out or reflecting a lot of light.
BRISK: Active, fast, and energetic.','2025-01-06 14:00:00','2025-01-06 14:00:00'),
('Level 88','','CAMP,CLAMP,CLAMPED,CLAMPING,CLAMPS','{"characters":["C","A","M","P","L"],"rows":[[{"key":"C","words":["CAMP"],"isShow":false},{"key":"A","words":["CAMP"],"isShow":false},{"key":"M","words":["CAMP"],"isShow":false},{"key":"P","words":["CAMP"],"isShow":false}],[{"key":"C","words":["CLAMP"],"isShow":false},{"key":"L","words":["CLAMP"],"isShow":false},{"key":"A","words":["CLAMP"],"isShow":false},{"key":"M","words":["CLAMP"],"isShow":false},{"key":"P","words":["CLAMP"],"isShow":false}],[{"key":"C","words":["CLAMPED"],"isShow":false},{"key":"L","words":["CLAMPED"],"isShow":false},{"key":"A","words":["CLAMPED"],"isShow":false},{"key":"M","words":["CLAMPED"],"isShow":false},{"key":"P","words":["CLAMPED"],"isShow":false},{"key":"E","words":["CLAMPED"],"isShow":false},{"key":"D","words":["CLAMPED"],"isShow":false}],[{"key":"C","words":["CLAMPING"],"isShow":false},{"key":"L","words":["CLAMPING"],"isShow":false},{"key":"A","words":["CLAMPING"],"isShow":false},{"key":"M","words":["CLAMPING"],"isShow":false},{"key":"P","words":["CLAMPING"],"isShow":false},{"key":"I","words":["CLAMPING"],"isShow":false},{"key":"N","words":["CLAMPING"],"isShow":false},{"key":"G","words":["CLAMPING"],"isShow":false}],[{"key":"C","words":["CLAMPS"],"isShow":false},{"key":"L","words":["CLAMPS"],"isShow":false},{"key":"A","words":["CLAMPS"],"isShow":false},{"key":"M","words":["CLAMPS"],"isShow":false},{"key":"P","words":["CLAMPS"],"isShow":false},{"key":"S","words":["CLAMPS"],"isShow":false}]]}','C,A,M,P,L','CAMP: A place with temporary accommodations.
CLAMP: A device used to hold something tightly.
CLAMPED: Held tightly with a clamp.
CLAMPING: The act of holding something tightly with a clamp.
CLAMPS: Devices used to hold things tightly.','2025-01-07 14:00:00','2025-01-07 14:00:00'),
('Level 89','','DANCE,DARE,DEAR,READ,RED','{"characters":["D","A","N","C","E"],"rows":[[{"key":"D","words":["DANCE"],"isShow":false},{"key":"A","words":["DANCE"],"isShow":false},{"key":"N","words":["DANCE"],"isShow":false},{"key":"C","words":["DANCE"],"isShow":false},{"key":"E","words":["DANCE"],"isShow":false}],[{"key":"D","words":["DARE"],"isShow":false},{"key":"A","words":["DARE"],"isShow":false},{"key":"R","words":["DARE"],"isShow":false},{"key":"E","words":["DARE"],"isShow":false}],[{"key":"D","words":["DEAR"],"isShow":false},{"key":"E","words":["DEAR"],"isShow":false},{"key":"A","words":["DEAR"],"isShow":false},{"key":"R","words":["DEAR"],"isShow":false}],[{"key":"R","words":["READ"],"isShow":false},{"key":"E","words":["READ"],"isShow":false},{"key":"A","words":["READ"],"isShow":false},{"key":"D","words":["READ"],"isShow":false}],[{"key":"R","words":["RED"],"isShow":false},{"key":"E","words":["RED"],"isShow":false},{"key":"D","words":["RED"],"isShow":false}]]}','D,A,N,C,E','DANCE: Move rhythmically to music.
DARE: Have the courage to do something.
DEAR: Regarded with deep affection.
READ: Look at and comprehend the meaning of written material.
RED: The color at the end of the spectrum next to orange.','2025-01-08 14:00:00','2025-01-08 14:00:00')
,
('Level 99','','FIRE,FRIED,FRIES,FRIES,FRIES','{"characters":["F","I","R","E","D"],"rows":[[{"key":"F","words":["FIRE"],"isShow":false},{"key":"I","words":["FIRE"],"isShow":false},{"key":"R","words":["FIRE"],"isShow":false},{"key":"E","words":["FIRE"],"isShow":false}],[{"key":"F","words":["FRIED"],"isShow":false},{"key":"R","words":["FRIED"],"isShow":false},{"key":"I","words":["FRIED"],"isShow":false},{"key":"E","words":["FRIED"],"isShow":false},{"key":"D","words":["FRIED"],"isShow":false}],[{"key":"F","words":["FRIES"],"isShow":false},{"key":"R","words":["FRIES"],"isShow":false},{"key":"I","words":["FRIES"],"isShow":false},{"key":"E","words":["FRIES"],"isShow":false},{"key":"S","words":["FRIES"],"isShow":false}]]}','F,I,R,E,D','FIRE: Combustion or burning.
FRIED: Cooked in hot fat or oil.
FRIES: Thin strips of fried potato.','2025-01-18 14:00:00','2025-01-18 14:00:00')
,
('Level 90','','EARTH,HEART,HATER,HEAT,TEAR','{"characters":["E","A","R","T","H"],"rows":[[{"key":"E","words":["EARTH"],"isShow":false},{"key":"A","words":["EARTH"],"isShow":false},{"key":"R","words":["EARTH"],"isShow":false},{"key":"T","words":["EARTH"],"isShow":false},{"key":"H","words":["EARTH"],"isShow":false}],[{"key":"H","words":["HEART"],"isShow":false},{"key":"E","words":["HEART"],"isShow":false},{"key":"A","words":["HEART"],"isShow":false},{"key":"R","words":["HEART"],"isShow":false},{"key":"T","words":["HEART"],"isShow":false}],[{"key":"H","words":["HATER"],"isShow":false},{"key":"A","words":["HATER"],"isShow":false},{"key":"T","words":["HATER"],"isShow":false},{"key":"E","words":["HATER"],"isShow":false},{"key":"R","words":["HATER"],"isShow":false}],[{"key":"H","words":["HEAT"],"isShow":false},{"key":"E","words":["HEAT"],"isShow":false},{"key":"A","words":["HEAT"],"isShow":false},{"key":"T","words":["HEAT"],"isShow":false}],[{"key":"T","words":["TEAR"],"isShow":false},{"key":"E","words":["TEAR"],"isShow":false},{"key":"A","words":["TEAR"],"isShow":false},{"key":"R","words":["TEAR"],"isShow":false}]]}','E,A,R,T,H','EARTH: The planet on which we live.
HEART: The organ that pumps blood.
HATER: A person who dislikes something intensely.
HEAT: The quality of being hot.
TEAR: A drop of clear salty liquid from the eyes.','2025-01-09 14:00:00','2025-01-09 14:00:00')